### ISSUE TITLE
Improve Question Spec (Stub/Mock)

### ISSUE THREAD

**Issue by fabienalbi** [liftoff-team/sarce-trainer-admin#39]
- [ ] Learn to use stubs and mocks 
- [ ] Apply on question spec

**Comment by ManyBaby** [comment]
@fabienalbi I don't know if you already use it but there is a nice feature in GitHub Flavored Markdown for adding checkboxes. Pretty useful.
- [ ] task 01
- [x] task 02
https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

**Comment by fabienalbi** [comment]
Yes ! Je le fait en temps normal 😃  Je modifie !
